export const SET_CHART_DATA = "SET_CHART_DATA";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

export const CURRENT_CHART = "CURRENT_CHART";
export const HISTORICAL_CHART = "HISTORICAL_CHART";